<%@page import="ume.pareva.dao.*,ume.pareva.userservice.*, ume.pareva.template.*, ume.pareva.sdk.*,ume.pareva.cms.*,ume.pareva.pojo.*" %>
<%@page import="java.util.*,java.text.*,java.io.*, javax.imageio.*, java.awt.*, java.awt.image.* "%>
<%@page import="org.springframework.web.servlet.support.RequestContextUtils"%>
<%@page import="org.springframework.context.ApplicationContext"%>
<%@page import="org.hibernate.Query"%>
<%@page import="org.hibernate.Session"%>
<%@page import="org.hibernate.SessionFactory"%>
<%@page import="org.hibernate.Transaction"%>
<%@page import="com.mitchellbosecke.pebble.template.PebbleTemplate"%>
<%@page import="com.mitchellbosecke.pebble.PebbleEngine"%>
<%@page import="com.mitchellbosecke.pebble.loader.ClasspathLoader"%>
<%@page import="com.mitchellbosecke.pebble.extension.escaper.EscaperExtension"%>
<%@page import="com.reporo.ads.ReporoAds,com.reporo.ads.ReporoAdBean"%>
